name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c03368460b1e2e9b8c3400145f7fe2fdf3145ae1891756358d78f9ee38fc95a"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
