name = "Refurbished Engineering Modpack test"
author = "Latitud"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a68e11d304d07af1e916e8de49d595ccd15cff2f0e72ac43a8f016df12f1c1da"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
