name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d188a2338d9c5fd31a8f33d72af9ee291688cea211fb6e3f50ec4bfb4ef6a8a"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
