name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32ef5e25c341a8b36479dc39216290f9d9c96f164090c24a981b6440268332c"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
