name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2d66327090f95648e1fc83995d7e3760191cc894af6cc83daa96833e13b9320"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
