name = "Refurbished Engineering"
author = "Latitud"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55f11a511f9fcfd8bab5c449b362bd6dff93c50f9f337ec233c9a4c51782b649"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
