name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f48497fe76dfec65626a7b0f0952621bf037c6b8bfc5e999ebbcfa1540a3d3f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
