name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e37128f6c7898b745e1fd652468bd838e269683a9bcfcd66bfb3e0d8fcbdf1"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
