name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72a8bdf58566bcb3b1c265d71cbd849774dc918f393ffd1bb61b0f9c45f56da"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
