name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb2d31a53480b7bec69b2c0757ae7e853f195080f06625c0a0a52a44d8c00c4c"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
