name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bedba9f625c945f4ec6764a05d8f541b833fb80f9e74f25b2d6b929fa8ef51a"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
