name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "419ea232e0d1b76960deaa783b7dc869a042879285b650e2aa77b0c84acd3705"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
