name = "Refurbished Engineering Modpack"
author = "Latitud"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17d1d71627650289c21e743beeb8adc0d05caa1de162a4d3a72889d158f5ba03"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
