name: Bundle Files

on:
  push:
    branches:
      - main
jobs:
  bundle_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download and Extract Zip File
        run: |
          mkdir downloaded_files
          curl -o downloaded_files/packwiz-installer-bootstrap.jar https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar
          curl -o downloaded_files/packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Windows%2064-bit.zip
          unzip downloaded_files/packwiz.zip -d downloaded_files
      - name: Bundle Files
        run: |
          mkdir bundle
          mv downloaded_files/packwiz.exe bundle/
          cp -r src/* bundle/
          zip -r bundle.zip bundle
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundled-files
          path: bundle.zip