name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          command: 'curl -o packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Windows%2064-bit.zip && curl -o packwiz-boostrap-instaler.jar https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar'
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: release.zip
