name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download binaries
        run: |
          mkdir -p src
          mv * src/
          mkdir mrpack
          cd mrpack
          curl -Lo packwiz-linux.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz-linux.zip
          rm -f packwiz-linux.zip
          cd ..
          cd src
          curl -Lo packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Windows%2064-bit.zip
          curl -Lo packwiz-boostrap-instaler.jar https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar
          unzip packwiz.zip
          rm -f packwiz.zip
          cd ..
      - name: Create Modrinth Pack
        run: |
          ./packwiz mr export
          rm -f packwiz
      - name: Exclude Files
        run: |
          find . -type f \( -name '.gitignore' -o -name '.gitattributes' -o -name 'LICENSE' \) -delete
          find . -type d \( -name '.git' -o -name '.github' \) -exec rm -r {} +
      - name: Upload Packwiz zip
        uses: actions/upload-artifact@v2
        with:
          name: Packwiz zip
          path: src
      - name: Upload Modrinth Pack
        uses: actions/upload-artifact@v2
        with:
          name: Modrinth Pack
          path: mrpack
