name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download binaries
        run: |
          mkdir -p src
          find . -type f | cpio -pdm src/
          cd src
          curl -Lo packwiz-linux.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz-linux.zip
          rm -f packwiz-linux.zip
          cd ..
      - name: Create Modrinth Pack
        run: |
          cd src
          chmod +x packwiz
          ./packwiz mr export
          rm -f packwiz
          mkdir ../mrpack
          mv *.mrpack ../mrpack
          cd ..
      - name: Upload Packwiz Pack
        uses: actions/upload-artifact@v2
        with:
          name: Packwiz Pack
          path: src
      - name: Upload Modrinth Pack
        uses: actions/upload-artifact@v2
        with:
          name: Modrinth Pack
          path: mrpack
