name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download binaries
        run: |
          # Add your commands here to create release.zip
          curl -Lo packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Windows%2064-bit.zip
          curl -Lo packwiz-boostrap-instaler.jar https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar
          unzip packwiz.zip
          rm -f packwiz.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: .
