name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Exclude Files
        run: |
          find . -type f \( -name '.gitignore' -o -name '.gitattributes' -o -name 'LICENSE' \) -delete
          find . -type d \( -name '.git' -o -name '.github' \) -exec rm -r {} +
      - name: Download binaries
        run: |
          mkdir -p src
          find . -type f | cpio -pdm src/
          cd src
          ls
          curl -Lo packwiz-linux.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz-linux.zip
          rm -f packwiz-linux.zip
          curl -Lo packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Windows%2064-bit.zip
          curl -Lo packwiz-boostrap-instaler.jar https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar
          unzip packwiz.zip
          rm -f packwiz.zip
          cd ..
      - name: Create Modrinth Pack
        run: |
          cd src
          chmod +x packwiz
          ./packwiz mr export
          rm -f packwiz
          mkdir mrpack
          mv *.mrpack mrpack/
      - name: Pre-upload moving
        run: |
          cd src
          find . -mindepth 1 -type d -not -name 'mrpack' -exec sh -c 'mkdir -p dist"$(dirname "{}")" && mv "{}" dist"$(dirname "{}")"' \;
          find . -mindepth 1 -type f -not -name 'mrpack' -exec mv "{}" dist"$(dirname "{}")" \;
      - name: Upload Packwiz zip
        uses: actions/upload-artifact@v2
        with:
          name: Packwiz zip
          path: src/dist
      - name: Upload Modrinth Pack
        uses: actions/upload-artifact@v2
        with:
          name: Modrinth Pack
          path: src/mrpack
